# Column Transformer on Titaninc Dataset

In [92]:
import numpy as np
import pandas as pd

In [93]:
df=pd.read_csv('Titanic-Dataset.csv')

In [94]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [95]:
df=df[['Sex','Age','Pclass','Embarked']]

In [96]:
df.shape

(891, 4)

In [97]:
df=df.iloc[0:100,0:4]

In [98]:
df

Sex   Age  Pclass Embarked
0     male  22.0       3        S
1   female  38.0       1        C
2   female  26.0       3        S
3   female  35.0       1        S
4     male  35.0       3        S
..     ...   ...     ...      ...
95    male   NaN       3        S
96    male  71.0       1        C
97    male  23.0       1        C
98  female  34.0       2        S
99    male  34.0       2        S

[100 rows x 4 columns]

In [99]:
df.shape

(100, 4)

In [100]:
df.isnull().sum()

Sex          0
Age         22
Pclass       0
Embarked     1
dtype: int64

In [101]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Embarked']),df['Embarked'],test_size=0.2)

In [102]:
X_train

Sex   Age  Pclass
3   female  35.0       1
60    male  22.0       3
9   female  14.0       2
32  female   NaN       3
70    male  32.0       2
..     ...   ...     ...
86    male  16.0       3
26    male   NaN       3
2   female  26.0       3
98  female  34.0       2
94    male  59.0       3

[80 rows x 3 columns]

In [103]:
y_train

3     S
60    C
9     C
32    Q
70    S
     ..
86    S
26    C
2     S
98    S
94    S
Name: Embarked, Length: 80, dtype: object

In [104]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [105]:
# applying imputer on age column
si = SimpleImputer()
age_train = si.fit_transform(X_train[['Age']])

age_test = si.fit_transform(X_test[['Age']])

age_train.shape

(80, 1)

In [106]:
age_train

array([[35.        ],
       [22.        ],
       [14.        ],
       [29.33327869],
       [32.        ],
       [34.        ],
       [ 7.        ],
       [71.        ],
       [23.        ],
       [22.        ],
       [21.        ],
       [29.33327869],
       [28.        ],
       [29.33327869],
       [39.        ],
       [14.        ],
       [ 2.        ],
       [26.        ],
       [29.33327869],
       [18.        ],
       [29.33327869],
       [16.        ],
       [45.        ],
       [31.        ],
       [49.        ],
       [29.33327869],
       [25.        ],
       [29.33327869],
       [40.        ],
       [29.33327869],
       [21.        ],
       [55.        ],
       [ 4.        ],
       [35.        ],
       [26.        ],
       [19.        ],
       [24.        ],
       [46.        ],
       [ 4.        ],
       [35.        ],
       [29.33327869],
       [28.        ],
       [40.        ],
       [20.        ],
       [29.33327869],
       [58

In [107]:
df

Sex   Age  Pclass Embarked
0     male  22.0       3        S
1   female  38.0       1        C
2   female  26.0       3        S
3   female  35.0       1        S
4     male  35.0       3        S
..     ...   ...     ...      ...
95    male   NaN       3        S
96    male  71.0       1        C
97    male  23.0       1        C
98  female  34.0       2        S
99    male  34.0       2        S

[100 rows x 4 columns]

In [108]:
# applying ordinal encoding on sex

oe = OrdinalEncoder(categories=[['male','female']])

sex_train = oe.fit_transform(X_train[['Sex']])

sex_test = oe.fit_transform(X_test[['Sex']])

sex_train.shape

(80, 1)

In [109]:
sex_train

array([[1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [110]:
# Onehotencoding on Pclass

ohe = OneHotEncoder(drop='first',sparse=False)

Pclass_train = ohe.fit_transform(X_train[['Pclass']])

Pclass_test = ohe.fit_transform(X_test[['Pclass']])

Pclass_train.shape

c:\Users\panka\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
c:\Users\panka\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 2)

In [111]:
X_train_trans = np.concatenate((age_train,sex_train,Pclass_train),axis=1)

X_test_trans = np.concatenate((age_test,sex_test,Pclass_test),axis=1)

In [112]:
X_test_trans.shape

(20, 4)

In [113]:
X_test_trans

array([[20.76470588,  0.        ,  0.        ,  1.        ],
       [11.        ,  0.        ,  0.        ,  1.        ],
       [ 8.        ,  1.        ,  0.        ,  1.        ],
       [66.        ,  0.        ,  1.        ,  0.        ],
       [17.        ,  1.        ,  1.        ,  0.        ],
       [ 3.        ,  1.        ,  1.        ,  0.        ],
       [22.        ,  0.        ,  0.        ,  1.        ],
       [27.        ,  1.        ,  1.        ,  0.        ],
       [29.        ,  0.        ,  0.        ,  1.        ],
       [27.        ,  1.        ,  0.        ,  1.        ],
       [20.        ,  0.        ,  0.        ,  1.        ],
       [17.        ,  1.        ,  0.        ,  1.        ],
       [38.        ,  1.        ,  0.        ,  0.        ],
       [19.        ,  0.        ,  0.        ,  0.        ],
       [20.76470588,  0.        ,  0.        ,  1.        ],
       [23.        ,  0.        ,  0.        ,  0.        ],
       [ 2.        ,  0.

- Column transformer

In [114]:

from sklearn.compose import ColumnTransformer

In [116]:
trans=ColumnTransformer(transformers=[
('tnf1',SimpleImputer(),['Age']),
('tnf2',OrdinalEncoder(categories=[['male','female']]),['Sex']),
('tnf3',OneHotEncoder(sparse=False,drop='first'),['Pclass'])
],remainder='passthrough')

In [117]:
trans

ColumnTransformer(remainder='passthrough',
                  transformers=[('tnf1', SimpleImputer(), ['Age']),
                                ('tnf2',
                                 OrdinalEncoder(categories=[['male',
                                                             'female']]),
                                 ['Sex']),
                                ('tnf3',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['Pclass'])])

In [118]:
trans.fit_transform(X_train)

c:\Users\panka\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[35.        ,  1.        ,  0.        ,  0.        ],
       [22.        ,  0.        ,  0.        ,  1.        ],
       [14.        ,  1.        ,  1.        ,  0.        ],
       [29.33327869,  1.        ,  0.        ,  1.        ],
       [32.        ,  0.        ,  1.        ,  0.        ],
       [34.        ,  0.        ,  1.        ,  0.        ],
       [ 7.        ,  0.        ,  0.        ,  1.        ],
       [71.        ,  0.        ,  0.        ,  0.        ],
       [23.        ,  1.        ,  0.        ,  0.        ],
       [22.        ,  0.        ,  0.        ,  1.        ],
       [21.        ,  0.        ,  0.        ,  1.        ],
       [29.33327869,  0.        ,  0.        ,  1.        ],
       [28.        ,  0.        ,  0.        ,  0.        ],
       [29.33327869,  0.        ,  0.        ,  1.        ],
       [39.        ,  0.        ,  0.        ,  1.        ],
       [14.        ,  1.        ,  0.        ,  1.        ],
       [ 2.        ,  0.

In [119]:
trans.fit_transform(X_train).shape

c:\Users\panka\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 4)